### ISSUE TITLE
拓展符号 ...  会在iPhone6s 上报错

### ISSUE THREAD

**Issue by zfz329114474** [shb190802/picture-compressor#1]
希望作者能编译一次，不要使用原文件，我目前是将代码直接复制到项目中使用，使用了 项目的babel。希望越来越好
这段代码 拓展符号 ... 报错，没有转义
image.onload = function() {
      const distSize = getDistSize({
        width: changeWidthAndHeight ? this.naturalHeight : this.naturalWidth,
        height: changeWidthAndHeight ? this.naturalWidth : this.naturalHeight
      }, {
        width: changeWidthAndHeight ? height : width,
        height: changeWidthAndHeight ? width : height
      }, fit)
      const imgData = compress(this, distSize.width, distSize.height, type, quality, rotate)
      resolve({
        ...distSize,
        img: imgData
      })
    }

**Comment by shb190802** [comment]
收到，谢谢了，很快就改。

**Comment by shb190802** [comment]
经过测试，未更新系统的iphone6s上，会出现此问题。已经修复。
同时版本中引用babel对项目做了编译。
谢谢你的建议。
